// Generated by gencpp from file my_first_package/multiplier.msg
// DO NOT EDIT!


#ifndef MY_FIRST_PACKAGE_MESSAGE_MULTIPLIER_H
#define MY_FIRST_PACKAGE_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <my_first_package/multiplierRequest.h>
#include <my_first_package/multiplierResponse.h>


namespace my_first_package
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace my_first_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_first_package::multiplier > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::my_first_package::multiplier&) { return value(); }
};

template<>
struct DataType< ::my_first_package::multiplier > {
  static const char* value()
  {
    return "my_first_package/multiplier";
  }

  static const char* value(const ::my_first_package::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::my_first_package::multiplierRequest> should match
// service_traits::MD5Sum< ::my_first_package::multiplier >
template<>
struct MD5Sum< ::my_first_package::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_package::multiplier >::value();
  }
  static const char* value(const ::my_first_package::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_package::multiplierRequest> should match
// service_traits::DataType< ::my_first_package::multiplier >
template<>
struct DataType< ::my_first_package::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::my_first_package::multiplier >::value();
  }
  static const char* value(const ::my_first_package::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_first_package::multiplierResponse> should match
// service_traits::MD5Sum< ::my_first_package::multiplier >
template<>
struct MD5Sum< ::my_first_package::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_package::multiplier >::value();
  }
  static const char* value(const ::my_first_package::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_package::multiplierResponse> should match
// service_traits::DataType< ::my_first_package::multiplier >
template<>
struct DataType< ::my_first_package::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::my_first_package::multiplier >::value();
  }
  static const char* value(const ::my_first_package::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_FIRST_PACKAGE_MESSAGE_MULTIPLIER_H
