// Generated by gencpp from file my_first_package/values.msg
// DO NOT EDIT!


#ifndef MY_FIRST_PACKAGE_MESSAGE_VALUES_H
#define MY_FIRST_PACKAGE_MESSAGE_VALUES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_first_package
{
template <class ContainerAllocator>
struct values_
{
  typedef values_<ContainerAllocator> Type;

  values_()
    : letter(0)  {
    }
  values_(const ContainerAllocator& _alloc)
    : letter(0)  {
  (void)_alloc;
    }



   typedef int64_t _letter_type;
  _letter_type letter;





  typedef boost::shared_ptr< ::my_first_package::values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_first_package::values_<ContainerAllocator> const> ConstPtr;

}; // struct values_

typedef ::my_first_package::values_<std::allocator<void> > values;

typedef boost::shared_ptr< ::my_first_package::values > valuesPtr;
typedef boost::shared_ptr< ::my_first_package::values const> valuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_first_package::values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_first_package::values_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_first_package::values_<ContainerAllocator1> & lhs, const ::my_first_package::values_<ContainerAllocator2> & rhs)
{
  return lhs.letter == rhs.letter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_first_package::values_<ContainerAllocator1> & lhs, const ::my_first_package::values_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_first_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_first_package::values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_first_package::values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_first_package::values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_first_package::values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_package::values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_package::values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_first_package::values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0aff0824e905c6e4dad564004ff12fa0";
  }

  static const char* value(const ::my_first_package::values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0aff0824e905c6e4ULL;
  static const uint64_t static_value2 = 0xdad564004ff12fa0ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_first_package::values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_first_package/values";
  }

  static const char* value(const ::my_first_package::values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_first_package::values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 letter\n"
;
  }

  static const char* value(const ::my_first_package::values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_first_package::values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.letter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_first_package::values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_first_package::values_<ContainerAllocator>& v)
  {
    s << indent << "letter: ";
    Printer<int64_t>::stream(s, indent + "  ", v.letter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_FIRST_PACKAGE_MESSAGE_VALUES_H
